// Menganggap tipe waktu Java sebagai stabil
java.time.LocalDate
java.time.LocalDateTime
java.time.LocalTime
java.time.YearMonth

// Menganggap tipe bawaan Kotlin eksternal sebagai stabil
kotlin.ByteArray

// (Opsional tapi direkomendasikan) Menganggap koleksi standar sebagai stabil
// Ini akan menghilangkan tanda "RUNTIME" pada parameter List Anda
kotlin.collections.*

// Menganggap ViewModel bawaan Android sebagai stabil
androidx.lifecycle.ViewModel
