// Menganggap tipe waktu Java sebagai stabil
java.time.LocalDate
java.time.LocalDateTime
java.time.LocalTime
java.time.YearMonth

// Menganggap tipe bawaan Kotlin eksternal sebagai stabil
kotlin.ByteArray

// BENAR: Sebutkan nama kelas koleksi secara spesifik
// Ini akan menghilangkan tanda "RUNTIME" atau "unstable" pada parameter List Anda
kotlin.collections.List
kotlin.collections.Set
kotlin.collections.Map

// Menganggap ViewModel bawaan Android sebagai stabil
androidx.lifecycle.ViewModel