name: Build Termux Wheels (Rust/Maturin)

on:
  workflow_dispatch:

jobs:
  build-android-wheels:
    name: Build ${{ matrix.package }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Isi dengan nama paket Rust yang ingin di-build
        package: 
          - "jiter"
          - "pydantic-core==2.27.2"

    steps:
      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Setup Zig (Linker untuk Termux/Android)
        uses: goto-bus-stop/setup-zig@v2

      - name: Workaround Sysconfig Android
        run: |
          # Trik untuk menipu Maturin & PyO3 agar menggunakan konfigurasi dari mesin Host Ubuntu
          # Karena untuk abi3, isi konfigurasinya sama persis
          STDLIB_PATH=$(python -c "import sysconfig; print(sysconfig.get_path('stdlib'))")
          INCLUDE_PATH=$(python -c "import sysconfig; print(sysconfig.get_path('include'))")
          
          echo "MATURIN_PYTHON_SYSCONFIGDATA_DIR=$STDLIB_PATH" >> $GITHUB_ENV
          echo "PYO3_CROSS_INCLUDE_DIR=$INCLUDE_PATH" >> $GITHUB_ENV
          echo "PYO3_CROSS_LIB_DIR=$STDLIB_PATH" >> $GITHUB_ENV
          echo "PYO3_CROSS_PYTHON_VERSION=3.11" >> $GITHUB_ENV

      - name: Download & Extract Source Code
        id: extract
        run: |
          pip download --no-binary :all: --no-deps ${{ matrix.package }}
          
          file=$(ls | grep -E '\.(tar\.gz|zip)$' | head -n 1)
          if [[ $file == *.zip ]]; then unzip "$file"; else tar -xzf "$file"; fi
          rm "$file"
          
          folder_name=$(find . -maxdepth 1 -type d ! -name "." | head -n 1)
          echo "src_dir=$folder_name" >> $GITHUB_OUTPUT

      - name: Build Wheel using Maturin Action
        uses: PyO3/maturin-action@v1
        with:
          working-directory: ${{ steps.extract.outputs.src_dir }}
          target: aarch64-linux-android
          manylinux: off
          command: build
          args: --release --zig --out ../final_wheels -i python3.11

      - name: Upload Wheel Artifact
        uses: actions/upload-artifact@v4
        with:
          name: termux-wheel-${{ matrix.package }}
          path: final_wheels/*.whl
