name: Android Release Build coba1

on:
  workflow_dispatch:

defaults:
  run:
    working-directory: ./coba

jobs:
  build:
    name: Build Release APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      # Setup Gradle dengan caching otomatis
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          gradle-version: wrapper
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}
          add-job-summary: on-failure

      - name: Grant Execute Permission for Gradlew
        run: chmod +x ./gradlew

      - name: Perform Gradle Sync
        run: ./gradlew help --parallel --build-cache

      # Build Release APK dengan optimasi
      - name: Build APK (Optimized)
        run: ./gradlew assembleRelease --parallel --build-cache --configuration-cache --stacktrace
        env:
          GRADLE_OPTS: "-Dorg.gradle.daemon=false"
          ORG_GRADLE_PROJECT_android_native_build_output_ignore_errors: true

      # Sign APK dengan action resmi
      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        env:
          BUILD_TOOLS_VERSION: "34.0.0"
        with:
          releaseDirectory: coba/app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.KEYSTORE_BASE64 }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      # Upload signed APK
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: pos-offline-release-signed-apk
          path: |
            ${{steps.sign_app.outputs.signedReleaseFile}}
            coba/app/**/*.json
          retention-days: 1
          if-no-files-found: error

      - name: Cleanup Runner Environment & Build Artifacts
        if: always() # Memastikan step ini SELALU berjalan (Sukses, Gagal, atau Dibatalkan)
        run: |
          echo "--- Memulai Pembersihan Runner & Bekas Build ---"
          
          # 1. Menghentikan Gradle Daemon agar RAM & CPU lega
          ./gradlew --stop || true
          
          # 3. Menjalankan task clean dari Gradle
          ./gradlew clean || true
          
          # 4. Hapus folder build dan .gradle secara paksa
          rm -rf build app/build .gradle || true
          
          # 5. Hapus semua file/folder yang tidak di-track oleh Git (bekas kompilasi, test report, APK temporer, dll)
          git clean -ffdx || true
          
          echo "--- Pembersihan Total Selesai ---"